name: Arduino Auto Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
        with:
          version: 0.35.3
          

      - name: Install AVR core
        run: arduino-cli core install arduino:avr

      - name: Compile all .ino sketches
        run: |
          for sketch in $(find . -name "*.ino"); do
            echo "Compiling $sketch ..."
            arduino-cli compile --fqbn arduino:avr:uno "$sketch"
          done
